<?php
return array(
	"The Journey of the Fifth Horse (TV)",
	"The Star Wagon (TV)",
	"The Tiger Makes Out d'Arthur Hiller",
	"Le Lauréat (The Graduate) de Mike Nichols",
	"Un Dollaro per 7 vigliacchi (Madigan's Millions)",
	"Sunday Father",
	"Macadam Cowboy (Midnight Cowboy) de John Schlesinger",
	"John et Mary (John and Mary) de Peter Yates",
	"Little Big Man (Little Big Man) d'Arthur Penn",
	"The Point (TV)",
	"Qui est Harry Kellerman ? (Who IsHarry Kellerman and Why Is He Saying Those Terrible Things About Me?) de Ulu Grosbard",
	"Les Chiens de paille (Straw Dogs) de Sam Peckinpah",
	"Alfredo, Alfredo de Pietro Germi",
	"Papillon de Franklin J. Schaffner",
	"Lenny de Bob Fosse",
	"Les Hommes du président (All the President's Men) de Alan J. Pakula",
	"Marathon Man de John Schlesinger",
	"Bette Midler",
	"Le Récidiviste (Straight Time) d'Ulu Grosbard",
	"Agatha de Michael Apted",
	"Kramer contre Kramer (Kramer vs. Kramer) de Robert Benton",
	"Tootsie de Sydney Pollack",
	"Mort d'un commis voyageur (Death of a Salesman) de Volker Schlöndorff (TV)",
	"Ishtar de Elaine May",
	"Rain Man de Barry Levinson",
	"Affaire de famille (Family Business) de Sidney Lumet",
	"Dick Tracy de Warren Beatty",
	"A Wish for Wings That Work (TV)",
	"Billy Bathgate de Robert Benton",
	"Hook ou la Revanche du Capitaine Crochet (Hook) de Steven Spielberg",
	"Les Simpson (1 épisode",
	"Héros malgré lui (Hero) de Stephen Frears",
	"La Classe américaine, de Michel Hazanavicius et Dominique Mézerette",
	"Alerte ! (Outbreak) de Wolfgang Petersen",
	"American Buffalo",
	"Sleepers de Barry Levinson",
	"Mad City de Costa-Gavras",
	"Des hommes d'influence (Wag the Dog) de Barry Levinson",
	"Sphère (Sphere) de Barry Levinson",
	"Jeanne d'Arc (The Messenger",
	"Moonlight Mile de Brad Silberling",
	"Confidence de James Foley",
	"Le Maître du jeu (Runaway Jury) de Gary Fleder",
	"Neverland (Finding Neverland) de Marc Forster",
	"J'adore Huckabees (I Heart Huckabees) de David O. Russell",
	"Les Désastreuses Aventures des orphelins Baudelaire (Lemony Snicket's A Series of Unfortunate Events) de Brad Silberling",
	"Mon beau-père, mes parents et moi (Meet the Fockers) de Jay Roach",
	"Zig Zag, l'étalon zébré (Racing Stripes) de Frederik Du Chau",
	"Adieu Cuba (The Lost City) d'Andy García",
	"Le Parfum, histoire d'un meurtrier (Perfume",
	"L'Incroyable Destin de Harold Crick (Stranger Than Fiction) de Marc Forster",
	"The Holiday de Nancy Meyers",
	"Kung Fu Panda",
	"Le Merveilleux Magasin de Mr. Magorium de Zach Helm",
	"La Légende de Despereaux de Sam Fell",
	"Last Chance for Love de Joel Hopkins",
	"Mon beau-père et nous (Little Fockers) de Paul Weitz",
	"Kung Fu Panda 2",
	"Le Monde de Barney de Richard J. Lewis"
);